console.group("Group 1")
console.log("message 1")
console.log("message 2")
console.groupCollapsed("Child group")
console.log("message 1")
console.log("message 2")
console.groupCollapsed("Grand Child group")
console.log("message 1")
console.log("message 2")
console.groupEnd()
console.groupEnd()
console.groupEnd()

console.group("Group 2")
console.log("message 1")
console.log("message 2")